POST https://1oe07ch4kf.execute-api.eu-central-1.amazonaws.com/dev/messages
Content-Type: application/json

{
    "message": "Hello, World!"
}
###
GET https://1oe07ch4kf.execute-api.eu-central-1.amazonaws.com/dev/messages